[package]
name = "fakeit-tech"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.1.1"
ctor = "0.6.3"
dirs = "6.0.0"
lazy_static = "1.5.0"
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.11"
